// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadDotenv } from "dotenv";
import { defineConfig } from "prisma/config";
import fs from "fs";

// Only load .env.local if it exists (avoids overwriting Docker env vars)
if (fs.existsSync(".env.local")) {
  loadDotenv({ path: ".env.local" });
} else if (fs.existsSync(".env")) {
  loadDotenv({ path: ".env" });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --require dotenv/config --require esbuild-register prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
